### ISSUE TITLE
Flaky Test: Coverage failing on a nil deref

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1032]
It happens quite often in our CI that the coverage test will fail on a nil dereference:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa6143b]
goroutine 223901 [running]:
github.com/drand/drand/chain/beacon.(*Handler).ProcessPartialBeacon(0xc008ebf9e0, {0xdcb7b8, 0xc005b838f0}, 0xc0040d1d50)
	/home/runner/work/drand/drand/chain/beacon/node.go:123 +0x6db
github.com/drand/drand/core.(*BeaconProcess).PartialBeacon(0xc007c19a40, {0xdcb7b8, 0xc005b838f0}, 0xc004ffb800)
	/home/runner/work/drand/drand/core/drand_beacon_public.go:55 +0x129
github.com/drand/drand/core.(*DrandDaemon).PartialBeacon(0x15, {0xdcb7b8, 0xc005b838f0}, 0xc0040d1d50)
	/home/runner/work/drand/drand/core/drand_daemon_public.go:29 +0xc5
github.com/drand/drand/protobuf/drand._Protocol_PartialBeacon_Handler.func1({0xdcb7b8, 0xc005b838f0}, {0xc56440, 0xc0040d1d50})
	/home/runner/work/drand/drand/protobuf/drand/protocol_grpc.pb.go:285 +0x8a
github.com/drand/drand/core.(*DrandDaemon).NodeVersionValidator(0xc00281aa20, {0xdcb7b8, 0xc005b838f0}, {0xc56440, 0xc0040d1d50}, 0x3, 0xc000d7bfc8)
	/home/runner/work/drand/drand/core/drand_daemon_interceptors.go:52 +0x47c
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0xdcb7b8, 0xc005b838f0}, {0xc56440, 0xc0040d1d50})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0xdcb7b8, 0xc005b838f0}, {0xc56440, 0xc0040d1d50}, 0x18, 0xc000bd0fe0)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0xdcb7b8, 0xc005b838f0}, {0xc56440, 0xc0040d1d50})
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0xdcb7b8, 0xc005b838f0}, {0xc56440, 0xc0040d1d50}, 0xc006445bb8, 0xbd4400)
	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34 +0xbf
github.com/drand/drand/protobuf/drand._Protocol_PartialBeacon_Handler({0xcab440, 0xc00281aa20}, {0xdcb7b8, 0xc005b838f0}, 0xc0007a6f00, 0xc00ae98840)
	/home/runner/work/drand/drand/protobuf/drand/protocol_grpc.pb.go:287 +0x17c
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00e0e21c0, {0xdd9c60, 0xc0057eb440}, 0xc00846fd40, 0xc00ae98a20, 0x1350400, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00e0e21c0, {0xdd9c60, 0xc0057eb440}, 0xc00846fd40, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x294
FAIL	github.com/drand/drand/core	48.931s
FAIL
```
e.g.: https://github.com/drand/drand/runs/6979696231?check_suite_focus=true

while running the `github.com/drand/drand/core` tests, it seems.

We should dig into how it's possible and correct it.

**Comment by CluEleSsUK** [comment]
not anymore
