### ISSUE TITLE
TestLocalOrchestration is flaky

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1160]
It often hangs while stopping the nodes, and stops responding. A quick fix in #1158 was to spin go routines to stop each node, but that still sometimes hangs, it seems or panic:
```
panic: failed to ping nodes in 30 seconds
goroutine 14 [running]:
github.com/drand/drand/demo/lib.(*Orchestrator).startNodes(0xc0004989c0, {0xc00009e540, 0x3, 0x0?})
/home/runner/work/drand/drand/demo/lib/orchestrator.go:149 +0x388
github.com/drand/drand/demo/lib.(*Orchestrator).StartCurrentNodes(0xc0004989c0, {0x0, 0x0, 0x0})
/home/runner/work/drand/drand/demo/lib/orchestrator.go:110 +0x90
github.com/drand/drand/demo_test.testLocalOrchestration(0xc0001a7d40)
/home/runner/work/drand/drand/demo/demo_test.go:58 +0x225
github.com/drand/drand/demo_test.TestLocalOrchestration.func1()
/home/runner/work/drand/drand/demo/demo_test.go:26 +0x73
created by github.com/drand/drand/demo_test.TestLocalOrchestration
/home/runner/work/drand/drand/demo/demo_test.go:23 +0x176
```

**Comment by CluEleSsUK** [comment]
no longer relevant
