### ISSUE TITLE
Error when using 'make demo' locally

### ISSUE THREAD

**Issue by RegisGraptin** [drand/drand#1394]
Hello, I am currently trying to run 'drand' locally, but comes to some issues...
When following the doc:

```bash
git clone https://github.com/drand/drand
cd drand
make install
make demo
```

I have this issue: 

```log
... /tmp/drand (master)$ make demo
cd demo && go build -tags conn_insecure && ./demo -build
[+] Building & installing drand
[+] Simulation global folder: /tmp/drand-full
[-] Error: exec: "drand": executable file not found in $PATH
[-] Command "drand generate-keypair --folder /tmp/drand-full/node-0 --id default --scheme pedersen-bls-chained 127.0.0.1:38637" gave

panic: exec: "drand": executable file not found in $PATH

goroutine 1 [running]:
github.com/drand/drand/v2/demo/node.runCommand(0xc000002480, {0x0, 0x0, 0x8?})
	/tmp/drand/demo/node/node_subprocess.go:462 +0x185
github.com/drand/drand/v2/demo/node.(*NodeProc).setup(0xc0000c6a00)
	/tmp/drand/demo/node/node_subprocess.go:128 +0x39a
github.com/drand/drand/v2/demo/node.NewNode(0x0, {0x6, 0x4, {0xe7d9e7, 0x2}, {0xe7ee3b, 0x5}, 0x1, 0xc00031a4d0, {0xe82547, ...}, ...})
	/tmp/drand/demo/node/node_subprocess.go:89 +0x551
github.com/drand/drand/v2/demo/lib.createNodes({0x6, 0x4, {0xe7d9e7, 0x2}, {0xe7ee3b, 0x5}, 0x1, 0xc00031a4d0, {0xe82547, 0x7}, ...})
	/tmp/drand/demo/lib/orchestrator.go:561 +0x1fb
github.com/drand/drand/v2/demo/lib.NewOrchestrator({0x6, 0x4, {0xe7d9e7, 0x2}, {0xe7ee3b, 0x5}, 0x1, 0xc00031a4d0, {0xe82547, 0x7}, ...})
	/tmp/drand/demo/lib/orchestrator.go:71 +0x1b8
main.main()
	/tmp/drand/demo/main.go:77 +0x2d8
make: *** [Makefile:121 : demo] Erreur 2
```

Telling me that drand is not in my PATH (I am on linux), so I added it using:
`export PATH="$PATH:/tmp/drand"`
Plus, I needed to build it using `make build`
=> Maybe we should add it in the doc? I mean, was not clear for me to begin with. And also, you maybe have a cleaner way of doing the PATH definition, I will take it :)

And finally, when doing a `make demo` again, I got this: 

```bash
.... /tmp/drand (master)$ make demo
cd demo && go build -tags conn_insecure && ./demo -build
[+] Building & installing drand
[+] Simulation global folder: /tmp/drand-full
	- Created node 127.0.0.1:37767 at /tmp/drand-full --> ctrl port: 40959
	- Created node 127.0.0.1:33963 at /tmp/drand-full --> ctrl port: 43621
	- Created node 127.0.0.1:38139 at /tmp/drand-full --> ctrl port: 45119
	- Created node 127.0.0.1:43415 at /tmp/drand-full --> ctrl port: 36189
	- Created node 127.0.0.1:43493 at /tmp/drand-full --> ctrl port: 41095
	- Created node 127.0.0.1:42263 at /tmp/drand-full --> ctrl port: 35013
[+] Setting up 3 new nodes for resharing
	- Created node 127.0.0.1:35211 at /tmp/drand-full --> ctrl port: 36943
	- Created node 127.0.0.1:38709 at /tmp/drand-full --> ctrl port: 42191
	- Created node 127.0.0.1:40811 at /tmp/drand-full --> ctrl port: 39387
[+] Starting all nodes
	- Starting node 127.0.0.1:37767
starting node 127.0.0.1:37767 with cmd: [start --folder /tmp/drand-full/node-0 --control 40959 --private-listen 0.0.0.0:37767 --public-listen 0.0.0.0:46765 --db bolt --pg-dsn  --memdb-size 2000 --verbose] 
	- Starting node 127.0.0.1:33963
starting node 127.0.0.1:33963 with cmd: [start --folder /tmp/drand-full/node-1 --control 43621 --private-listen 0.0.0.0:33963 --public-listen 0.0.0.0:43245 --db bolt --pg-dsn  --memdb-size 2000 --verbose] 
	- Starting node 127.0.0.1:42263
starting node 127.0.0.1:42263 with cmd: [start --folder /tmp/drand-full/node-5 --control 35013 --private-listen 0.0.0.0:42263 --public-listen 0.0.0.0:44877 --db bolt --pg-dsn  --memdb-size 2000 --verbose] 
	- Starting node 127.0.0.1:43493
starting node 127.0.0.1:43493 with cmd: [start --folder /tmp/drand-full/node-4 --control 41095 --private-listen 0.0.0.0:43493 --public-listen 0.0.0.0:35815 --db bolt --pg-dsn  --memdb-size 2000 --verbose] 
	- Starting node 127.0.0.1:43415
starting node 127.0.0.1:43415 with cmd: [start --folder /tmp/drand-full/node-3 --control 36189 --private-listen 0.0.0.0:43415 --public-listen 0.0.0.0:34101 --db bolt --pg-dsn  --memdb-size 2000 --verbose] 
	- Starting node 127.0.0.1:38139
starting node 127.0.0.1:38139 with cmd: [start --folder /tmp/drand-full/node-2 --control 45119 --private-listen 0.0.0.0:38139 --public-listen 0.0.0.0:33881 --db bolt --pg-dsn  --memdb-size 2000 --verbose] 
 -- ping output : drand daemon is alive on port 40959

 -- ping output : drand daemon is alive on port 43621

 -- ping output : drand daemon is alive on port 35013

 -- ping output : drand daemon is alive on port 41095

 -- ping output : drand daemon is alive on port 36189

 -- ping output : drand daemon is alive on port 45119

[+] Running DKG for all nodes
	- Running DKG for leader node 127.0.0.1:37767
[-] Error: signal: killed
[-] Command "drand dkg init --genesis-delay 20s --control 40959 --id default --scheme pedersen-bls-chained --period 3s --catchup-period 1s --proposal /tmp/drand-full/node-0/proposal.toml --threshold 4 --timeout 5m0s" gave

make: *** [Makefile:121 : demo] Erreur 1
```

I am assuming I maybe missed something or I am doing something wrong here. Let me know if I can provided you more info on this. Maybe some logs? Or if I need to use other commands, to fully initialize my env? Thanks.

**Comment by kenyiu** [comment]
Hi @RegisGraptin , may i know the following if you are still facing the issue?
1. Go version
2. the result of `go install`
3. Linux version

Thanks!

**Comment by ayu-ch** [comment]
Yep, since Go installs binaries like drand into `$HOME/go/bin`, you need to add that directory to your `PATH` so you can run them from anywhere in your terminal :)
