### ISSUE TITLE
new panic

### ISSUE THREAD

**Issue by nikkolasg** [drand/drand#146]
panic: dkg: own deal gave a complaint

goroutine 1847 [running]:
github.com/dedis/drand/vendor/go.dedis.ch/kyber/v3/share/dkg/pedersen.(*DistKeyGenerator).Deals(0xc0005f0b00, 0xc0001dc730, 0xc000240060, 0x2)
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/go.dedis.ch/kyber/v3/share/dkg/pedersen/dkg.go:282 +0x407
github.com/dedis/drand/dkg.(*Handler).sendDeals(0xc000095930, 0xb4e918, 0xc000095930)
        /home/ubuntu/go/src/github.com/dedis/drand/dkg/dkg.go:413 +0x77
github.com/dedis/drand/dkg.(*Handler).Start(0xc000095930)
        /home/ubuntu/go/src/github.com/dedis/drand/dkg/dkg.go:174 +0x67
github.com/dedis/drand/core.(*Drand).StartDKG(0xc00043ad20, 0xc0001b0f80, 0x2)
        /home/ubuntu/go/src/github.com/dedis/drand/core/drand.go:127 +0x60
github.com/dedis/drand/core.(*Drand).startResharingAsLeader(0xc00043ad20, 0x5)
        /home/ubuntu/go/src/github.com/dedis/drand/core/drand_control.go:203 +0x56c
github.com/dedis/drand/core.(*Drand).InitReshare(0xc00043ad20, 0xc10000, 0xc000593200, 0xc0005c7540, 0xc00043ad20, 0xc000593200, 0xc0000ceba8)
        /home/ubuntu/go/src/github.com/dedis/drand/core/drand_control.go:164 +0x382
github.com/dedis/drand/protobuf/drand._Control_InitReshare_Handler(0xb0b680, 0xc00043ad20, 0xc10000, 0xc000593200, 0xc0005c74f0, 0x0, 0xc10000, 0xc000593200, 0xc0002f7c20, 0x25)
        /home/ubuntu/go/src/github.com/dedis/drand/protobuf/drand/control.pb.go:967 +0x23e
github.com/dedis/drand/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001cc180, 0xc15b60, 0xc0003d2c00, 0xc0005e5400, 0xc0001b36e0, 0x10f4bd0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/google.golang.org/grpc/server.go:972 +0x470
github.com/dedis/drand/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001cc180, 0xc15b60, 0xc0003d2c00, 0xc0005e5400, 0x0)
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/google.golang.org/grpc/server.go:1252 +0xda6
github.com/dedis/drand/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002b44d0, 0xc0001cc180, 0xc15b60, 0xc0003d2c00, 0xc0005e5400)
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/google.golang.org/grpc/server.go:691 +0x9fpanic: dkg: own deal gave a complaint

goroutine 1847 [running]:
github.com/dedis/drand/vendor/go.dedis.ch/kyber/v3/share/dkg/pedersen.(*DistKeyGenerator).Deals(0xc0005f0b00, 0xc0001dc730, 0xc000240060, 0x2)
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/go.dedis.ch/kyber/v3/share/dkg/pedersen/dkg.go:282 +0x407
github.com/dedis/drand/dkg.(*Handler).sendDeals(0xc000095930, 0xb4e918, 0xc000095930)
        /home/ubuntu/go/src/github.com/dedis/drand/dkg/dkg.go:413 +0x77
github.com/dedis/drand/dkg.(*Handler).Start(0xc000095930)
        /home/ubuntu/go/src/github.com/dedis/drand/dkg/dkg.go:174 +0x67
github.com/dedis/drand/core.(*Drand).StartDKG(0xc00043ad20, 0xc0001b0f80, 0x2)
        /home/ubuntu/go/src/github.com/dedis/drand/core/drand.go:127 +0x60
github.com/dedis/drand/core.(*Drand).startResharingAsLeader(0xc00043ad20, 0x5)
        /home/ubuntu/go/src/github.com/dedis/drand/core/drand_control.go:203 +0x56c
github.com/dedis/drand/core.(*Drand).InitReshare(0xc00043ad20, 0xc10000, 0xc000593200, 0xc0005c7540, 0xc00043ad20, 0xc000593200, 0xc0000ceba8)
        /home/ubuntu/go/src/github.com/dedis/drand/core/drand_control.go:164 +0x382
github.com/dedis/drand/protobuf/drand._Control_InitReshare_Handler(0xb0b680, 0xc00043ad20, 0xc10000, 0xc000593200, 0xc0005c74f0, 0x0, 0xc10000, 0xc000593200, 0xc0002f7c20, 0x25)
        /home/ubuntu/go/src/github.com/dedis/drand/protobuf/drand/control.pb.go:967 +0x23e
github.com/dedis/drand/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001cc180, 0xc15b60, 0xc0003d2c00, 0xc0005e5400, 0xc0001b36e0, 0x10f4bd0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/google.golang.org/grpc/server.go:972 +0x470
github.com/dedis/drand/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0001cc180, 0xc15b60, 0xc0003d2c00, 0xc0005e5400, 0x0)
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/google.golang.org/grpc/server.go:1252 +0xda6
github.com/dedis/drand/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002b44d0, 0xc0001cc180, 0xc15b60, 0xc0003d2c00, 0xc0005e5400)
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/google.golang.org/grpc/server.go:691 +0x9f
created by github.com/dedis/drand/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/google.golang.org/grpc/server.go:689 +0xa1

created by github.com/dedis/drand/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/ubuntu/go/src/github.com/dedis/drand/vendor/google.golang.org/grpc/server.go:689 +0xa1

**Comment by nikkolasg** [comment]
hints #1 maybe the order changed when saving the file.

**Comment by nikkolasg** [comment]
DKG logic changed in [kyber](https://github.com/drand/kyber) and there are no panics anymore.
