### ISSUE TITLE
Illegal instruction when generating key on docker

### ISSUE THREAD

**Issue by lbarman** [drand/drand#210]
Hi, I'm facing a small issue:

ls -al:
```
ls -al
drwxr-----  2 root root 4096 Apr  9 10:16 data
-rw-r--r--  1 root root  224 Apr  9 10:24 docker-compose.yml
```
(data is empty)

docker-compose.yml:
```
version: '3'

services:
  drand:
    image: drandorg/go-drand:latest
    volumes:
      - ./data:/root/.drand
    ports:
      - "0.0.0.0:8019:8080"
    entrypoint: drand 
    command: generate-keypair drand.lbarman.ch:443
```
docker-compose up --build:
```
Attaching to drand_drand_1
drand_1  | drand v0.6-2-ge47cc20 (date 08/04/2020@22:55:49, commit e47cc20324efc001b3081c8e3ea9002be7a089ad) by nikkolasg
drand_1  | WARNING: this software has NOT received a full audit and must be used with caution and probably NOT in a production environment.
drand_1  | Generating private / public key pair with TLS indication
drand_1  | SIGILL: illegal instruction
drand_1  | PC=0x8c4a3c m=0 sigcode=2
drand_1  | 
drand_1  | goroutine 1 [running]:
drand_1  | github.com/drand/bls12-381.montmul_bmi2(0xc000078390, 0xc0001401b0, 0xc0001401b0)
drand_1  | 	/go/pkg/mod/github.com/drand/bls12-381@v0.0.0-20200110233355-faca855b3a67/arithmetic_bmi2.s:27 +0x2c fp=0xc000125820 sp=0xc000125800 pc=0x8c4a3c
drand_1  | github.com/drand/bls12-381.(*fp).square(...)
drand_1  | 	/go/pkg/mod/github.com/drand/bls12-381@v0.0.0-20200110233355-faca855b3a67/fp_common.go:163
drand_1  | github.com/drand/bls12-381.(*G1).Double(0xc000082aa0, 0xc0001401b0, 0xc0001401b0, 0xc000078420)
drand_1  | 	/go/pkg/mod/github.com/drand/bls12-381@v0.0.0-20200110233355-faca855b3a67/g1.go:308 +0xf9 fp=0xc000125898 sp=0xc000125820 pc=0x8b6e39
drand_1  | github.com/drand/bls12-381.(*G1).MulScalar(0xc000082aa0, 0xc000140000, 0xc000140090, 0xc0000eced0, 0x0)
drand_1  | 	/go/pkg/mod/github.com/drand/bls12-381@v0.0.0-20200110233355-faca855b3a67/g1.go:362 +0xcb fp=0xc0001258f0 sp=0xc000125898 pc=0x8b743b
drand_1  | github.com/drand/bls12-381.(*KyberG1).Mul(0xc000010350, 0xc13640, 0xc0000eced0, 0xc13040, 0xc000010358, 0xc00000ad00, 0x39)
drand_1  | 	/go/pkg/mod/github.com/drand/bls12-381@v0.0.0-20200110233355-faca855b3a67/kyber_g1.go:93 +0xd2 fp=0xc0001259c0 sp=0xc0001258f0 pc=0x8bc4b2
drand_1  | github.com/drand/drand/key.NewKeyPair(0x7ffc0aa6ff28, 0x14, 0xc000125b98)
drand_1  | 	/go/src/github.com/drand/drand/key/keys.go:48 +0x148 fp=0xc000125a48 sp=0xc0001259c0 pc=0x8ffd68
drand_1  | github.com/drand/drand/key.NewTLSKeyPair(...)
drand_1  | 	/go/src/github.com/drand/drand/key/keys.go:62
drand_1  | main.keygenCmd(0xc00005d100, 0x0, 0xc00005cfe0)
drand_1  | 	/go/src/github.com/drand/drand/main.go:486 +0xa5c fp=0xc000125c38 sp=0xc000125a48 pc=0x9a806c
drand_1  | main.main.func5(0xc00005d100, 0x3, 0x4)
drand_1  | 	/go/src/github.com/drand/drand/main.go:234 +0x30 fp=0xc000125c60 sp=0xc000125c38 pc=0x9ac730
drand_1  | github.com/urfave/cli/v2.(*Command).Run(0xc0001045a0, 0xc00005cf80, 0x0, 0x0)
drand_1  | 	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x499 fp=0xc000125d20 sp=0xc000125c60 pc=0x98bf99
drand_1  | github.com/urfave/cli/v2.(*App).RunContext(0xc000001500, 0xc099a0, 0xc000028038, 0xc000020180, 0x3, 0x3, 0x0, 0x0)
drand_1  | 	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x791 fp=0xc000125e28 sp=0xc000125d20 pc=0x9896c1
drand_1  | github.com/urfave/cli/v2.(*App).Run(...)
drand_1  | 	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
drand_1  | main.main()
drand_1  | 	/go/src/github.com/drand/drand/main.go:383 +0x1930 fp=0xc000125f98 sp=0xc000125e28 pc=0x9a59f0
drand_1  | runtime.main()
drand_1  | 	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000125fe0 sp=0xc000125f98 pc=0x42f5bc
drand_1  | runtime.goexit()
drand_1  | 	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000125fe8 sp=0xc000125fe0 pc=0x459b81
drand_1  | 
drand_1  | rax    0xc25f1572e1a87b0e
drand_1  | rbx    0x8c4a10
drand_1  | rcx    0x459e0d9452d611e4
drand_1  | rdx    0x5cb38790fd530c16
drand_1  | rdi    0xc0001401b0
drand_1  | rsi    0xc0001401b0
drand_1  | rbp    0xc000125810
drand_1  | rsp    0xc000125800
drand_1  | r8     0x2191875712a0301e
drand_1  | r9     0x2b7cd71362065849
drand_1  | r10    0xc0001401b0
drand_1  | r11    0x1
drand_1  | r12    0xffffffffffffffff
drand_1  | r13    0x4
drand_1  | r14    0x3
drand_1  | r15    0x38
drand_1  | rip    0x8c4a3c
drand_1  | rflags 0x10246
drand_1  | cs     0x33
drand_1  | fs     0x0
drand_1  | gs     0x0
drand_drand_1 exited with code 2
```

**Comment by lbarman** [comment]
Closing, my server did not have Intel ADX instruction set. It's patched in `docker-good` branch by nikkolasg.

**Comment by nikkolasg** [comment]
@lbarman it's merged on master now it should be fixed
