### ISSUE TITLE
crash when dkg ends unsuccessfully

### ISSUE THREAD

**Issue by willscott** [drand/drand#634]
```
all=drand_control.go:263 level=info dkg_setup=already_in_progress restart=dkg
panic: runtime error: invalid memory address or nil pointer dereference
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb1f4ef]
goroutine 59 [running]:
github.com/drand/drand/core.(*setupReceiver).stop(...)
    drand/core/group_setup.go:347
github.com/drand/drand/core.(*Drand).setupAutomaticDKG.func1(0xc00013a300)
    drand/core/drand_control.go:276 +0x4f
panic(0xc2f380, 0x1412160)
```

**Comment by emmanuelm41** [comment]
@yiannisbot @nikkolasg 

I am not sure when this issue was created. Some days before creating it, this commit was sent
https://github.com/drand/drand/blob/f991dc71a36771ff3558ab7cc4076441fe462a7e/core/drand_control.go#L250-L253

It should check receiver value and avoid the possible `nil` value. Could this bug happen anyway?

**Comment by AnomalRoil** [comment]
I think this cannot happen anymore, but I'm not sure what were the steps to reproduce it?
