### ISSUE TITLE
Devnet was reset to round 1 and continued from there

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#855]
On Oct 29th there was an automatic deployment to devnet:

```
 Oct 29 15:17:00 drand.dev1.drand systemd Starting installation of drand @ branch/master...
Oct 29 15:17:01 drand.dev1.drand install_program.sh drand checked-out version: a93f2b1
Oct 29 15:17:01 drand.dev1.drand install_program.sh drand installed version: 1311d66
Oct 29 15:17:05 drand.dev1.drand drand
2021-10-29T15:17:05.584Z        DEBUG        beacon/node.go:105                {"beacon_id": "", "received": "request", "from": "10.0.0.96:19860", "round": 389}
Oct 29 15:17:05 drand.dev1.drand drand
2021-10-29T15:17:05.591Z        DEBUG        beacon/node.go:133                {"beacon_id": "", "process_partial": "10.0.0.96:19860", "prev_sig": "b075d7", "curr_round": 1606897, "msg_sign": "71573b", "short_pub": "82aab", "status": "OK"}
Oct 29 15:17:05 drand.dev1.drand drand
2021-10-29T15:17:05.592Z        DEBUG        beacon/chain.go:120                {"beacon_id": "", "ignoring_partial": 389, "last_beacon_stored": 1606896}
Oct 29 15:17:05 drand.dev1.drand drand
2021-10-29T15:17:05.934Z        DEBUG        beacon/node.go:315                {"beacon_id": "", "beacon_loop": "new_round", "round": 1606897, "lastbeacon": 1606896}
Oct 29 15:17:05 drand.dev1.drand drand
2021-10-29T15:17:05.938Z        DEBUG        beacon/node.go:376                {"beacon_id": "", "broadcast_partial": 1606897, "from_prev_sig": "831ba6", "msg_sign": "eafdeb"}
Oct 29 15:17:05 drand.dev1.drand drand
2021-10-29T15:17:05.938Z        DEBUG        beacon/node.go:393                {"beacon_id": "", "beacon_round": 1606897, "send_to": "dev2.rpc.drand.sh:4444"}
Oct 29 15:17:05 drand.dev1.drand drand
2021-10-29T15:17:05.939Z        DEBUG        beacon/chain.go:137                {"beacon_id": "", "store_partial": "dev1.rpc.drand.sh:4444", "round": 1606897, "len_partials": "1/2"}
Oct 29 15:17:15 drand.dev1.drand install_program.sh go build -o drand -mod=readonly -ldflags "-X github.com/drand/drand/common.MAJOR=0 -X github.com/drand/drand/common.MINOR=0 -X github.com/drand/drand/common.PATCH=0 -X github.com/drand/drand/cmd/drand-cli.buildDate=29/10/2021@15:17:15 -X github.com/drand/drand/cmd/drand-cli.gitCommit=a93f2b13dfff2a1a31733b795af94edbab01400e"
Oct 29 15:17:17 drand.dev1.drand systemd Stopping drand...
Oct 29 15:17:17 drand.dev1.drand systemd Stopped drand.
Oct 29 15:17:17 drand.dev1.drand systemd Started drand.
Oct 29 15:17:17 drand.dev1.drand install_program.sh Successfully upgraded drand from 1311d66 to a93f2b1
Oct 29 15:17:17 drand.dev1.drand systemd Started installation of drand @ branch/master.
Oct 29 15:17:17 drand.dev1.drand drand fatal error: runtime: out of memory
Oct 29 15:17:17 drand.dev1.drand drand runtime stack:
Oct 29 15:17:17 drand.dev1.drand drand runtime.throw({0xc357d1, 0x64000000})
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/panic.go:1198 +0x71
Oct 29 15:17:17 drand.dev1.drand drand runtime.sysMap(0xc000400000, 0x42b5a0, 0x7ffc41136a88)
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/mem_linux.go:169 +0x96
Oct 29 15:17:17 drand.dev1.drand drand runtime.(*mheap).grow(0x1282ee0, 0x31e94)
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/mheap.go:1393 +0x225
Oct 29 15:17:17 drand.dev1.drand drand runtime.(*mheap).allocSpan(0x1282ee0, 0x31e94, 0x0, 0x1)
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/mheap.go:1179 +0x165
Oct 29 15:17:17 drand.dev1.drand drand runtime.(*mheap).alloc.func1()
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/mheap.go:913 +0x69
Oct 29 15:17:17 drand.dev1.drand drand runtime.systemstack()
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/asm_amd64.s:383 +0x49
Oct 29 15:17:17 drand.dev1.drand drand goroutine 1 [running]:
Oct 29 15:17:17 drand.dev1.drand drand runtime.systemstack_switch()
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/asm_amd64.s:350 fp=0xc0001c58b8 sp=0xc0001c58b0 pc=0x467a60
Oct 29 15:17:17 drand.dev1.drand drand runtime.(*mheap).alloc(0xc00003a000, 0xc0001c5968, 0x7b, 0x0)
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/mheap.go:907 +0x73 fp=0xc0001c5908 sp=0xc0001c58b8 pc=0x4278d3
Oct 29 15:17:17 drand.dev1.drand drand runtime.(*mcache).allocLarge(0xc0001c59c0, 0x63d27001, 0x60, 0x1)
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/mcache.go:227 +0x89 fp=0xc0001c5968 sp=0xc0001c5908 pc=0x418549
Oct 29 15:17:17 drand.dev1.drand drand runtime.mallocgc(0x63d27001, 0xb11d20, 0x1)
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/malloc.go:1082 +0x5c5 fp=0xc0001c59e8 sp=0xc0001c5968 pc=0x40e905
Oct 29 15:17:17 drand.dev1.drand drand runtime.makeslice(0xc0000107b0, 0x1d, 0x0)
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/slice.go:98 +0x52 fp=0xc0001c5a10 sp=0xc0001c59e8 pc=0x44e552
Oct 29 15:17:17 drand.dev1.drand drand os.ReadFile({0xc0000af840, 0x31})
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/os/file.go:693 +0xee fp=0xc0001c5af0 sp=0xc0001c5a10 pc=0x4d754e
Oct 29 15:17:17 drand.dev1.drand drand github.com/drand/drand/fs.CopyFile({0xc0000af840, 0x2}, {0xc000039580, 0x31})
Oct 29 15:17:17 drand.dev1.drand drand /opt/drand/fs/fs.go:141 +0x28 fp=0xc0001c5b30 sp=0xc0001c5af0 pc=0x896988
Oct 29 15:17:17 drand.dev1.drand drand github.com/drand/drand/fs.CopyFolder({0xc0000acaf8, 0x14}, {0xc000098de0, 0x28})
Oct 29 15:17:17 drand.dev1.drand drand /opt/drand/fs/fs.go:166 +0x1cc fp=0xc0001c5bc8 sp=0xc0001c5b30 pc=0x896bec
Oct 29 15:17:17 drand.dev1.drand drand github.com/drand/drand/core/migration.MigrateSBFolderStructure({0xc0000ac6f0, 0x11})
Oct 29 15:17:17 drand.dev1.drand drand /opt/drand/core/migration/migration.go:92 +0x9ba fp=0xc0001c5cd8 sp=0xc0001c5bc8 pc=0xa4b55a
Oct 29 15:17:17 drand.dev1.drand drand github.com/drand/drand/cmd/drand-cli.runMigration(0xc00000cb40)
Oct 29 15:17:17 drand.dev1.drand drand /opt/drand/cmd/drand-cli/cli.go:571 +0x28 fp=0xc0001c5cf8 sp=0xc0001c5cd8 pc=0xaa7c88
Oct 29 15:17:17 drand.dev1.drand drand github.com/urfave/cli/v2.(*Command).Run(0x12582a0, 0xc0001aea40)
Oct 29 15:17:17 drand.dev1.drand systemd drand.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 29 15:17:17 drand.dev1.drand drand /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:151 +0x5c4 fp=0xc0001c5df0 sp=0xc0001c5cf8 pc=0xa64b04
Oct 29 15:17:17 drand.dev1.drand drand github.com/urfave/cli/v2.(*App).RunContext(0xc0000e6900, {0xd2c868, 0xc000036060}, {0xc0000320c0, 0xc, 0xc})
Oct 29 15:17:17 drand.dev1.drand drand /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x926 fp=0xc0001c5f28 sp=0xc0001c5df0 pc=0xa625c6
Oct 29 15:17:17 drand.dev1.drand drand github.com/urfave/cli/v2.(*App).Run(...)
Oct 29 15:17:17 drand.dev1.drand drand /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
Oct 29 15:17:17 drand.dev1.drand drand main.main()
Oct 29 15:17:17 drand.dev1.drand drand /opt/drand/main.go:12 +0x45 fp=0xc0001c5f80 sp=0xc0001c5f28 pc=0xab2a45
Oct 29 15:17:17 drand.dev1.drand drand runtime.main()
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc0001c5fe0 sp=0xc0001c5f80 pc=0x439a47
Oct 29 15:17:17 drand.dev1.drand drand runtime.goexit()
Oct 29 15:17:17 drand.dev1.drand drand /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0001c5fe8 sp=0xc0001c5fe0 pc=0x469c81
Oct 29 15:17:17 drand.dev1.drand systemd Unit drand.service entered failed state.
Oct 29 15:17:17 drand.dev1.drand systemd drand.service failed.
Oct 29 15:17:22 drand.dev1.drand systemd drand.service holdoff time over, scheduling restart.
Oct 29 15:17:22 drand.dev1.drand systemd Stopped drand.
Oct 29 15:17:22 drand.dev1.drand systemd Started drand.
Oct 29 15:17:22 drand.dev1.drand drand drand 0.0.0 (date 29/10/2021@15:17:15, commit a93f2b13dfff2a1a31733b795af94edbab01400e) by nikkolasg
Oct 29 15:17:22 drand.dev1.drand drand drand: will already start running randomness beacon. BeaconID: [default]
Oct 29 15:17:22 drand.dev1.drand drand
2021-10-29T15:17:22.769Z        INFO        core/drand.go:124                {"network": "init", "insecure": true}
Oct 29 15:17:22 drand.dev1.drand drand
2021-10-29T15:17:22.770Z        INFO        core/drand.go:141                {"private_listen": "0.0.0.0:4444", "control_port": "8888", "public_listen": "0.0.0.0:5555", "folder": "/mnt/drand/.drand/multibeacon"}
Oct 29 15:17:22 drand.dev1.drand drand
2021-10-29T15:17:22.785Z        DEBUG        core/drand.go:165                {"beacon_id": "", "serving": "dev1.rpc.drand.sh:4444"}
Oct 29 15:17:22 drand.dev1.drand drand
2021-10-29T15:17:22.795Z        INFO        core/drand.go:237                {"beacon_id": "", "beacon_start": "2021-10-29T15:17:22.795Z", "catchup": true}
Oct 29 15:17:22 drand.dev1.drand drand
2021-10-29T15:17:22.796Z        DEBUG        beacon/sync.go:81                {"beacon_id": "", "syncer": "starting", "up_to": 1606898, "nodes": "[ dev2.rpc.drand.sh:4444 - dev1.rpc.drand.sh:4444 ]"}
Oct 29 15:17:22 drand.dev1.drand drand
2021-10-29T15:17:22.796Z        DEBUG        beacon/node.go:291                {"beacon_id": "", "run_round": "wait", "until": 1635520650}
Oct 29 15:17:23 drand.dev1.drand drand
2021-10-29T15:17:23.131Z        DEBUG        beacon/sync.go:116                {"beacon_id": "", "syncer": "start_follow", "with_peer": "dev2.rpc.drand.sh:4444", "from_round": 1}
Oct 29 15:17:23 drand.dev1.drand drand
2021-10-29T15:17:23.341Z        DEBUG        beacon/sync.go:119                {"beacon_id": "", "syncer": "new_beacon_fetched", "with_peer": "dev2.rpc.drand.sh:4444", "from_round": 1, "got_round": 1}
Oct 29 15:17:23 drand.dev1.drand drand
2021-10-29T15:17:23.349Z        INFO        beacon/store.go:83                {"beacon_id": "", "NEW_BEACON_STORED": "{ round: 1, sig: 946a7b, prevSig: 567d47 }", "time_discrepancy_ms": 40172418349.66382}
```

Translation:
  * Drand version went from:  1311d66 to a93f2b1
  * drand ran out of memory on start with the new version
  * drand restarted on round 1, although it realizes that it should be way later
  * drand churns along from round 1.
  * Exactly the same happened on the other node that is part of the network.

**Comment by nikkolasg** [comment]
Seems like they coudn't find the database and they try to sync with each other but both are at the same step so they are syncing with each other, but still slowly because now we are delaying syncing by some seconds.

**Comment by hsanjuan** [comment]
Debug logs on re-start show certain sync attempts which they are failling at:

```
 Nov 19 16:41:06 drand.dev1.drand drand drand 0.0.0 (date 10/11/2021@21:05:49, commit b30b07425f96f4ba41912ed6066cc7a8e899be80) by nikkolasg
Nov 19 16:41:06 drand.dev1.drand drand drand: will already start running randomness beacon. BeaconID: [default]
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.267Z        INFO        core/drand.go:127                {"network": "init", "insecure": true}
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.268Z        INFO        core/drand.go:144                {"private_listen": "0.0.0.0:4444", "control_port": "8888", "public_listen": "0.0.0.0:5555", "folder": "/mnt/drand/.drand/multibeacon"}
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.283Z        DEBUG        core/drand.go:168                {"beacon_id": "", "serving": "dev1.rpc.drand.sh:4444"}
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.290Z        INFO        core/drand.go:240                {"beacon_id": "", "beacon_start": "2021-11-19T16:41:06.290Z", "catchup": true}
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.290Z        DEBUG        beacon/sync.go:81                {"beacon_id": "", "syncer": "starting", "up_to": 1679675, "nodes": "[ dev2.rpc.drand.sh:4444 - dev1.rpc.drand.sh:4444 ]"}
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.291Z        DEBUG        beacon/node.go:291                {"beacon_id": "", "run_round": "wait", "until": 1637340075}
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.636Z        DEBUG        beacon/sync.go:116                {"beacon_id": "", "syncer": "start_follow", "with_peer": "dev2.rpc.drand.sh:4444", "from_round": 219288}
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.743Z        DEBUG        beacon/sync.go:119                {"beacon_id": "", "syncer": "new_beacon_fetched", "with_peer": "dev2.rpc.drand.sh:4444", "from_round": 219288, "got_round": 219288}
Nov 19 16:41:06 drand.dev1.drand drand
2021-11-19T16:41:06.752Z        INFO        beacon/store.go:83                {"beacon_id": "", "NEW_BEACON_STORED": "{ round: 219288, sig: b04905, prevSig: b3eb57 }", "time_discrepancy_ms": 36509666752.81056}
Nov 19 16:41:07 drand.dev1.drand drand
2021-11-19T16:41:07.449Z        DEBUG        core/drand_public.go:108                {"request": "stream", "from": "10.0.128.40:56386", "round": 0}
Nov 19 16:41:07 drand.dev1.drand drand
2021-11-19T16:41:07.718Z        DEBUG        core/drand_public.go:108                {"request": "stream", "from": "10.0.0.162:33978", "round": 0}
Nov 19 16:41:15 drand.dev1.drand drand
2021-11-19T16:41:15.291Z        DEBUG        beacon/node.go:315                {"beacon_id": "", "beacon_loop": "new_round", "round": 1679675, "lastbeacon": 219288}
Nov 19 16:41:15 drand.dev1.drand drand
2021-11-19T16:41:15.296Z        DEBUG        beacon/node.go:376                {"beacon_id": "", "broadcast_partial": 219289, "from_prev_sig": "b04905", "msg_sign": "49908e"}
Nov 19 16:41:15 drand.dev1.drand drand
2021-11-19T16:41:15.296Z        DEBUG        beacon/node.go:328                {"beacon_id": "", "beacon_loop": "run_sync_catchup", "last_is": "{ round: 219288, sig: b04905, prevSig: b3eb57 }", "should_be": 1679675}
Nov 19 16:41:15 drand.dev1.drand drand
2021-11-19T16:41:15.297Z        DEBUG        beacon/chain.go:223                {"beacon_id": "", "chain_store": "follow_finished", "err": "already following chain"}
```

**Comment by willscott** [comment]
that part i think is expected - they're doing the thing where they are in 'slow catchup' each time they restart. they realize they're way behind, but are only generating a new beacon every 10 or 15 seconds so that if there were clients depending on them, they would be able to stay in sync through the catch-up

**Comment by jleni** [comment]
> drand ran out of memory on start with the new version

I am interested in the reason for `MigrateSBFolderStructure` to run out of memory. I have not looked at the details yet but I think this is a key point to look at.

```
Oct 29 15:17:17 drand.dev1.drand drand github.com/drand/drand/core/migration.MigrateSBFolderStructure({0xc0000ac6f0, 0x11})
Oct 29 15:17:17 drand.dev1.drand drand /opt/drand/core/migration/migration.go:92 +0x9ba fp=0xc0001c5cd8 sp=0xc0001c5bc8 pc=0xa4b55a
Oct 29 15:17:17 drand.dev1.drand drand github.com/drand/drand/cmd/drand-cli.runMigration(0xc00000cb40)
```

> drand restarted on round 1, although it realizes that it should be way later

We will also try to improve logging a bit so more data about what triggers a migration and related information. 
It is good to have more information about this too.

Probably data was corrupted by the "bad" migration and the that triggered all this syncing from block 1, etc.

**Comment by jleni** [comment]
My initial hunch is that a partial migration took place and then data was corrupted and the node started anyway using the new newly migrated and incomplete data.

**Comment by emmanuelm41** [comment]
I guess the issue was generated by the file size of the db. The network had 2 million rounds, so I guess db file is really large. When we tried to move the file, it got an "out of memory" error. Before the error happened, the folder had been created. When the daemon ran again, the migration was completed, as multi beacon folder was created (check the following code)

https://github.com/drand/drand/blob/a93f2b13dfff2a1a31733b795af94edbab01400e/core/migration/migration.go#L15-L28

 We must take two things into account:
- Handle migration of big files
- Revert migration process is something fails

**Comment by nikkolasg** [comment]
Awesome that you found the reason, that's reassuring !
Yeah the second point is paramount imo, if we abort and clearly shows the
error (and that we catch any error that can happen and put it up in the
stack) then operator will know that he needs more space or memory etc.
Can you take this on a PR ?

**Comment by emmanuelm41** [comment]
@nikkolasg done!
