### ISSUE TITLE
[Tests] Weird failure

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#930]
To investigate:

```
[+] Stopping node 127.0.0.1:33721 to simulate a node failure
2022-03-09T12:59:57.068Z	DEBUG	beacon/node.go:353		{"beacon_id": "", "beacon_loop": "finished"}
2022-03-09T12:59:57.068Z	INFO	beacon/node.go:427		{"beacon_id": "", "beacon": "stop"}
2022-03-09T12:59:57.070Z	ERROR	node/node_inprocess.go:313		{"drand": "failed to shutdown", "err": "rpc error: code = Unavailable desc = error reading from server: EOF"}
[+] Sleeping 7s to reach round 4 + 3s
2022-03-09T13:00:00.987Z	DEBUG	beacon/node.go:320		{"beacon_id": "", "beacon_loop": "new_round", "round": 4, "lastbeacon": 3}
2022-03-09T13:00:00.991Z	DEBUG	beacon/node.go:381		{"beacon_id": "", "broadcast_partial": 4, "from_prev_sig": "af0d6f", "msg_sign": "59edf5"}
2022-03-09T13:00:00.991Z	DEBUG	beacon/node.go:398		{"beacon_id": "", "beacon_round": 4, "send_to": "127.0.0.1:44101"}
2022-03-09T13:00:00.992Z	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:45095", "round": 4, "len_partials": "1/2"}
2022-03-09T13:00:00.992Z	DEBUG	beacon/node.go:398		{"beacon_id": "", "beacon_round": 4, "send_to": "127.0.0.1:33721"}
2022-03-09T13:00:00.992Z	ERROR	beacon/node.go:401		{"beacon_id": "", "beacon_round": 4, "err_request": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:33721: connect: connection refused\"", "from": "127.0.0.1:33721"}
2022-03-09T13:00:00.992Z	DEBUG	beacon/node.go:106		{"beacon_id": "", "received": "request", "from": "127.0.0.1:37762", "round": 4}
2022-03-09T13:00:00.997Z	DEBUG	beacon/node.go:136		{"beacon_id": "", "process_partial": "127.0.0.1:37762", "prev_sig": "af0d6f", "curr_round": 4, "msg_sign": "59edf5", "from_node": "127.0.0.1:45095", "status": "OK"}
2022-03-09T13:00:00.997Z	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:37762", "round": 4, "len_partials": "1/2"}
2022-03-09T13:00:00.997Z	DEBUG	beacon/node.go:320		{"beacon_id": "", "beacon_loop": "new_round", "round": 4, "lastbeacon": 3}
2022-03-09T13:00:01.000Z	DEBUG	beacon/node.go:381		{"beacon_id": "", "broadcast_partial": 4, "from_prev_sig": "af0d6f", "msg_sign": "59edf5"}
2022-03-09T13:00:01.000Z	DEBUG	beacon/node.go:398		{"beacon_id": "", "beacon_round": 4, "send_to": "127.0.0.1:45095"}
2022-03-09T13:00:01.000Z	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:44101", "round": 4, "len_partials": "2/2"}
2022-03-09T13:00:01.000Z	DEBUG	beacon/node.go:398		{"beacon_id": "", "beacon_round": 4, "send_to": "127.0.0.1:33721"}
2022-03-09T13:00:01.000Z	ERROR	beacon/node.go:401		{"beacon_id": "", "beacon_round": 4, "err_request": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:33721: connect: connection refused\"", "from": "127.0.0.1:33721"}
2022-03-09T13:00:01.001Z	DEBUG	beacon/node.go:106		{"beacon_id": "", "received": "request", "from": "127.0.0.1:49700", "round": 4}
2022-03-09T13:00:01.005Z	DEBUG	beacon/node.go:136		{"beacon_id": "", "process_partial": "127.0.0.1:49700", "prev_sig": "af0d6f", "curr_round": 4, "msg_sign": "59edf5", "from_node": "127.0.0.1:44101", "status": "OK"}
2022-03-09T13:00:01.005Z	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:49700", "round": 4, "len_partials": "2/2"}
2022-03-09T13:00:01.020Z	INFO	beacon/chain.go:169		{"beacon_id": "", "aggregated_beacon": 4}
2022-03-09T13:00:01.028Z	INFO	beacon/store.go:120		{"beacon_id": "", "NEW_BEACON_STORED": "{ round: 4, sig: ae0677, prevSig: af0d6f }", "time_discrepancy_ms": 1028.106335}
2022-03-09T13:00:01.031Z	INFO	beacon/chain.go:169		{"beacon_id": "", "aggregated_beacon": 4}
2022-03-09T13:00:01.033Z	INFO	beacon/store.go:120		{"beacon_id": "", "NEW_BEACON_STORED": "{ round: 4, sig: ae0677, prevSig: af0d6f }", "time_discrepancy_ms": 1033.356318}
2022-03-09T13:00:03.942Z	DEBUG	core/drand_beacon_control.go:887		{"beacon_id": "", "phaser_finished": "response"}
2022-03-09T13:00:03.944Z	DEBUG	core/drand_beacon_control.go:887		{"beacon_id": "", "phaser_finished": "response"}
exit status 1make: *** [Makefile:73: coverage] Error 1
2022-03-09T13:00:03.950Z	DEBUG	core/drand_beacon_control.go:887		{"beacon_id": "", "phaser_finished": "response"}
2022-03-09T13:00:04.987Z	DEBUG	beacon/node.go:320		{"beacon_id": "", "beacon_loop": "new_round", "round": 5, "lastbeacon": 4}
2022-03-09T13:00:04.989Z	DEBUG	beacon/node.go:381		{"beacon_id": "", "broadcast_partial": 5, "from_prev_sig": "ae0677", "msg_sign": "bb3195"}
2022-03-09T13:00:04.990Z	DEBUG	beacon/node.go:398		{"beacon_id": "", "beacon_round": 5, "send_to": "127.0.0.1:44101"}
2022-03-09T13:00:04.990Z	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:45095", "round": 5, "len_partials": "1/2"}
2022-03-09T13:00:04.990Z	DEBUG	beacon/node.go:398		{"beacon_id": "", "beacon_round": 5, "send_to": "127.0.0.1:33721"}
2022-03-09T13:00:04.990Z	ERROR	beacon/node.go:401		{"beacon_id": "", "beacon_round": 5, "err_request": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:33721: connect: connection refused\"", "from": "127.0.0.1:33721"}
2022-03-09T13:00:04.990Z	DEBUG	beacon/node.go:106		{"beacon_id": "", "received": "request", "from": "127.0.0.1:37762", "round": 5}
2022-03-09T13:00:04.995Z	DEBUG	beacon/node.go:136		{"beacon_id": "", "process_partial": "127.0.0.1:37762", "prev_sig": "ae0677", "curr_round": 5, "msg_sign": "bb3195", "from_node": "127.0.0.1:45095", "status": "OK"}
2022-03-09T13:00:04.995Z	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:37762", "round": 5, "len_partials": "1/2"}
2022-03-09T13:00:04.998Z	DEBUG	beacon/node.go:320		{"beacon_id": "", "beacon_loop": "new_round", "round": 5, "lastbeacon": 4}
[+] Checking randomness beacon for round 5 via CLI
2022-03-09T13:00:05.001Z	DEBUG	beacon/node.go:381		{"beacon_id": "", "broadcast_partial": 5, "from_prev_sig": "ae0677", "msg_sign": "bb3195"}
2022-03-09T13:00:05.001Z	DEBUG	beacon/node.go:398		{"beacon_id": "", "beacon_round": 5, "send_to": "127.0.0.1:45095"}
2022-03-09T13:00:05.001Z	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:44101", "round": 5, "len_partials": "2/2"}
2022-03-09T13:00:05.006Z	DEBUG	beacon/node.go:106		{"beacon_id": "", "received": "request", "from": "127.0.0.1:49700", "round": 5}
2022-03-09T13:00:05.012Z	DEBUG	beacon/node.go:136		{"beacon_id": "", "process_partial": "127.0.0.1:49700", "prev_sig": "ae0677", "curr_round": 5, "msg_sign": "bb3195", "from_node": "127.0.0.1:44101", "status": "OK"}
2022-03-09T13:00:05.014Z	DEBUG	beacon/chain.go:144		{"beacon_id": "", "store_partial": "127.0.0.1:49700", "round": 5, "len_partials": "2/2"}
2022-03-09T13:00:05.017Z	DEBUG	beacon/node.go:398		{"beacon_id": "", "beacon_round": 5, "send_to": "127.0.0.1:33721"}
2022-03-09T13:00:05.018Z	ERROR	beacon/node.go:401		{"beacon_id": "", "beacon_round": 5, "err_request": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:33721: connect: connection refused\"", "from": "127.0.0.1:33721"}
2022-03-09T13:00:05.018Z	INFO	beacon/chain.go:169		{"beacon_id": "", "aggregated_beacon": 5}
2022-03-09T13:00:05.019Z	INFO	beacon/store.go:120		{"beacon_id": "", "NEW_BEACON_STORED": "{ round: 5, sig: b92516, prevSig: ae0677 }", "time_discrepancy_ms": 1019.82585}
2022-03-09T13:00:05.020Z	INFO	core/drand_beacon_public.go:81		{"public_rand": "127.0.0.1:37828", "round": 5, "reply": "{ round: 5, sig: b92516, prevSig: ae0677 }"}
	 - Example command is: "unused"
2022-03-09T13:00:05.026Z	DEBUG	core/drand_beacon_public.go:78		{"public_rand": "unstored_beacon", "round": 5, "from": "127.0.0.1:49766"}
2022-03-09T13:00:05.026Z	ERROR	node/node_inprocess.go:286		{"drand": "can't get becon", "err": "rpc error: code = Unknown desc = can't retrieve beacon: beacon not found in database <nil>"}
[+] Shutdown all nodes
	- Stop old node 127.0.0.1:33721
	- Stop old node 127.0.0.1:45095
	- Stop old node 127.0.0.1:44101
2022-03-09T13:00:05.026Z	ERROR	node/node_inprocess.go:313		{"drand": "failed to shutdown", "err": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:40287: connect: connection refused\""}
2022-03-09T13:00:05.026Z	INFO	beacon/node.go:427		{"beacon_id": "", "beacon": "stop"}
2022-03-09T13:00:05.027Z	INFO	beacon/node.go:427		{"beacon_id": "", "beacon": "stop"}
2022-03-09T13:00:05.027Z	DEBUG	beacon/node.go:353		{"beacon_id": "", "beacon_loop": "finished"}
2022-03-09T13:00:05.027Z	DEBUG	beacon/node.go:353		{"beacon_id": "", "beacon_loop": "finished"}
2022-03-09T13:00:05.031Z	ERROR	node/node_inprocess.go:313		{"drand": "failed to shutdown", "err": "rpc error: code = Unavailable desc = error reading from server: EOF"}
	- Successfully stopped Node 2 ( 127.0.0.1:45095 )
2022-03-09T13:00:05.031Z	ERROR	node/node_inprocess.go:313		{"drand": "failed to shutdown", "err": "rpc error: code = Unavailable desc = error reading from server: EOF"}
	- Successfully stopped Node 3 ( 127.0.0.1:44101 )
2022-03-09T13:00:05.032Z	INFO	beacon/chain.go:169		{"beacon_id": "", "aggregated_beacon": 5}
2022-03-09T13:00:05.032Z	ERROR	beacon/chain.go:201		{"beacon_id": "", "chain_store": "error storing beacon", "err": "database not open"}
2022-03-09T13:00:05.032Z	DEBUG	beacon/chain.go:176		{"beacon_id": "", "new_aggregated": "not_appendable", "last": "{ round: 4, sig: ae0677, prevSig: af0d6f }", "new": "{ round: 5, sig: b92516, prevSig: ae0677 }"}
2022-03-09T13:00:13.942Z	DEBUG	core/drand_beacon_control.go:887		{"beacon_id": "", "phaser_finished": "justification"}
2022-03-09T13:00:13.944Z	DEBUG	core/drand_beacon_control.go:887		{"beacon_id": "", "phaser_finished": "justification"}
2022-03-09T13:00:13.951Z	DEBUG	core/drand_beacon_control.go:887		{"beacon_id": "", "phaser_finished": "justification"}
--- FAIL: TestLocalOrchestration (34.32s)

FAIL	github.com/drand/drand/demo	34.339s
FAIL
```

With the following panic:
```
panic: [-] Inconsistent beacon signature between nodes [recovered]
	panic: [-] Inconsistent beacon signature between nodes

goroutine 19 [running]:
testing.tRunner.func1.2({0xb395a0, 0xd3ba70})
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1212 +0x218
panic({0xb395a0, 0xd3ba70})
	/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1038 +0x215
github.com/drand/drand/demo/lib.(*Orchestrator).checkBeaconNodes(0xc000092340, {0xc0000de840, 0x2, 0xc00066df18}, {0xc0000a28c0, 0x1a}, 0x0)
	/home/runner/work/drand/drand/demo/lib/orchestrator.go:296 +0x145a
github.com/drand/drand/demo/lib.(*Orchestrator).CheckCurrentBeacon(0xc000092340, {0xc00066df18, 0x1, 0x0})
	/home/runner/work/drand/drand/demo/lib/orchestrator.go:251 +0x85
github.com/drand/drand/demo.TestLocalOrchestration(0x407eb9)
	/home/runner/work/drand/drand/demo/demo_test.go:37 +0x1d1
testing.tRunner(0xc00020ad00, 0xc8d870)
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.17.7/x64/src/testing/testing.go:1306 +0x35a
	```

**Comment by AnomalRoil** [comment]
As usual in the coverage test.

https://github.com/drand/drand/actions/runs/1957309155/attempts/2
