### ISSUE TITLE
NewTCPGrpcControlListener return without erroring out.

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#948]
This is the snippet responsible for the issue:
https://github.com/drand/drand/blob/2700ed5ebcd719059c9751ef022a64cceae77a96/net/control.go#L33-L37

This can cause nil dereferences in cases where an error occurs (already [seen on our CI](https://github.com/drand/drand/runs/5757087998)):
```
 2022-03-30T15:45:19.232Z	ERROR	net/control.go:35		{"grpc listener": "failure", "err": "listen tcp 127.0.0.1:45599: bind: address already in use"}
2022-03-30T15:45:19.232Z	INFO	127.0.0.1:39931	core/drand_daemon.go:144	DrandDaemon initialized	{"private_listen": "127.0.0.1:39931", "control_port": "45599", "public_listen": "", "folder": "/tmp/drand3938590639/drand-3/multibeacon"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb22d5f]

goroutine 33743 [running]:
google.golang.org/grpc.(*Server).Serve(0x0, {0x0, 0x0})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:747 +0x5f
github.com/drand/drand/net.(*ControlListener).Start(0xc005368e28)
	/home/runner/work/drand/drand/net/control.go:45 +0x65
created by github.com/drand/drand/core.(*DrandDaemon).init
	/home/runner/work/drand/drand/core/drand_daemon.go:142 +0x9dd
FAIL	github.com/drand/drand/core	68.294s
```

**Comment by CluEleSsUK** [comment]
no longer exists
